//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("LVDatabaseModel", "FK_BANGTHAN_CO_THANH__NGUOICHO", "NGUOICHOI", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LVService1.NGUOICHOI), "BANGTHANHTICH", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LVService1.BANGTHANHTICH), true)]
[assembly: EdmRelationshipAttribute("LVDatabaseModel", "FK_BANGTHAN_THAM_GIA_MUCDO", "MUCDO", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LVService1.MUCDO), "BANGTHANHTICH", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LVService1.BANGTHANHTICH), true)]
[assembly: EdmRelationshipAttribute("LVDatabaseModel", "FK_PHONGCHO_CHON_HINH_HINHANH", "HINHANH", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LVService1.HINHANH), "PHONGCHOI", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LVService1.PHONGCHOI), true)]
[assembly: EdmRelationshipAttribute("LVDatabaseModel", "FK_PHONGCHO_CHON_MUC__MUCDO", "MUCDO", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LVService1.MUCDO), "PHONGCHOI", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LVService1.PHONGCHOI), true)]
[assembly: EdmRelationshipAttribute("LVDatabaseModel", "FK_TROCHUYE_RELATIONS_NGUOICHO", "NGUOICHOI", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LVService1.NGUOICHOI), "TROCHUYEN", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LVService1.TROCHUYEN), true)]
[assembly: EdmRelationshipAttribute("LVDatabaseModel", "FK_TROCHUYE_RELATIONS_PHONGCHO", "PHONGCHOI", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LVService1.PHONGCHOI), "TROCHUYEN", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LVService1.TROCHUYEN), true)]

#endregion

namespace LVService1
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class LVDatabaseEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new LVDatabaseEntities object using the connection string found in the 'LVDatabaseEntities' section of the application configuration file.
        /// </summary>
        public LVDatabaseEntities() : base("name=LVDatabaseEntities", "LVDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LVDatabaseEntities object.
        /// </summary>
        public LVDatabaseEntities(string connectionString) : base(connectionString, "LVDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LVDatabaseEntities object.
        /// </summary>
        public LVDatabaseEntities(EntityConnection connection) : base(connection, "LVDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BANGTHANHTICH> BANGTHANHTICHes
        {
            get
            {
                if ((_BANGTHANHTICHes == null))
                {
                    _BANGTHANHTICHes = base.CreateObjectSet<BANGTHANHTICH>("BANGTHANHTICHes");
                }
                return _BANGTHANHTICHes;
            }
        }
        private ObjectSet<BANGTHANHTICH> _BANGTHANHTICHes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BBXH_ONLINE> BBXH_ONLINE
        {
            get
            {
                if ((_BBXH_ONLINE == null))
                {
                    _BBXH_ONLINE = base.CreateObjectSet<BBXH_ONLINE>("BBXH_ONLINE");
                }
                return _BBXH_ONLINE;
            }
        }
        private ObjectSet<BBXH_ONLINE> _BBXH_ONLINE;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<HINHANH> HINHANHs
        {
            get
            {
                if ((_HINHANHs == null))
                {
                    _HINHANHs = base.CreateObjectSet<HINHANH>("HINHANHs");
                }
                return _HINHANHs;
            }
        }
        private ObjectSet<HINHANH> _HINHANHs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MUCDO> MUCDOes
        {
            get
            {
                if ((_MUCDOes == null))
                {
                    _MUCDOes = base.CreateObjectSet<MUCDO>("MUCDOes");
                }
                return _MUCDOes;
            }
        }
        private ObjectSet<MUCDO> _MUCDOes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NGUOICHOI> NGUOICHOIs
        {
            get
            {
                if ((_NGUOICHOIs == null))
                {
                    _NGUOICHOIs = base.CreateObjectSet<NGUOICHOI>("NGUOICHOIs");
                }
                return _NGUOICHOIs;
            }
        }
        private ObjectSet<NGUOICHOI> _NGUOICHOIs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PHONGCHOI> PHONGCHOIs
        {
            get
            {
                if ((_PHONGCHOIs == null))
                {
                    _PHONGCHOIs = base.CreateObjectSet<PHONGCHOI>("PHONGCHOIs");
                }
                return _PHONGCHOIs;
            }
        }
        private ObjectSet<PHONGCHOI> _PHONGCHOIs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TROCHUYEN> TROCHUYENs
        {
            get
            {
                if ((_TROCHUYENs == null))
                {
                    _TROCHUYENs = base.CreateObjectSet<TROCHUYEN>("TROCHUYENs");
                }
                return _TROCHUYENs;
            }
        }
        private ObjectSet<TROCHUYEN> _TROCHUYENs;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BANGTHANHTICHes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBANGTHANHTICHes(BANGTHANHTICH bANGTHANHTICH)
        {
            base.AddObject("BANGTHANHTICHes", bANGTHANHTICH);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BBXH_ONLINE EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBBXH_ONLINE(BBXH_ONLINE bBXH_ONLINE)
        {
            base.AddObject("BBXH_ONLINE", bBXH_ONLINE);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the HINHANHs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHINHANHs(HINHANH hINHANH)
        {
            base.AddObject("HINHANHs", hINHANH);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MUCDOes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMUCDOes(MUCDO mUCDO)
        {
            base.AddObject("MUCDOes", mUCDO);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NGUOICHOIs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNGUOICHOIs(NGUOICHOI nGUOICHOI)
        {
            base.AddObject("NGUOICHOIs", nGUOICHOI);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PHONGCHOIs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPHONGCHOIs(PHONGCHOI pHONGCHOI)
        {
            base.AddObject("PHONGCHOIs", pHONGCHOI);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TROCHUYENs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTROCHUYENs(TROCHUYEN tROCHUYEN)
        {
            base.AddObject("TROCHUYENs", tROCHUYEN);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LVDatabaseModel", Name="BANGTHANHTICH")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BANGTHANHTICH : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BANGTHANHTICH object.
        /// </summary>
        /// <param name="tAIKHOAN">Initial value of the TAIKHOAN property.</param>
        /// <param name="iDMUCDO">Initial value of the IDMUCDO property.</param>
        public static BANGTHANHTICH CreateBANGTHANHTICH(global::System.String tAIKHOAN, global::System.Int32 iDMUCDO)
        {
            BANGTHANHTICH bANGTHANHTICH = new BANGTHANHTICH();
            bANGTHANHTICH.TAIKHOAN = tAIKHOAN;
            bANGTHANHTICH.IDMUCDO = iDMUCDO;
            return bANGTHANHTICH;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TAIKHOAN
        {
            get
            {
                return _TAIKHOAN;
            }
            set
            {
                if (_TAIKHOAN != value)
                {
                    OnTAIKHOANChanging(value);
                    ReportPropertyChanging("TAIKHOAN");
                    _TAIKHOAN = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("TAIKHOAN");
                    OnTAIKHOANChanged();
                }
            }
        }
        private global::System.String _TAIKHOAN;
        partial void OnTAIKHOANChanging(global::System.String value);
        partial void OnTAIKHOANChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDMUCDO
        {
            get
            {
                return _IDMUCDO;
            }
            set
            {
                if (_IDMUCDO != value)
                {
                    OnIDMUCDOChanging(value);
                    ReportPropertyChanging("IDMUCDO");
                    _IDMUCDO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDMUCDO");
                    OnIDMUCDOChanged();
                }
            }
        }
        private global::System.Int32 _IDMUCDO;
        partial void OnIDMUCDOChanging(global::System.Int32 value);
        partial void OnIDMUCDOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SOBUOC
        {
            get
            {
                return _SOBUOC;
            }
            set
            {
                OnSOBUOCChanging(value);
                ReportPropertyChanging("SOBUOC");
                _SOBUOC = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SOBUOC");
                OnSOBUOCChanged();
            }
        }
        private Nullable<global::System.Int32> _SOBUOC;
        partial void OnSOBUOCChanging(Nullable<global::System.Int32> value);
        partial void OnSOBUOCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String THOIGIAN
        {
            get
            {
                return _THOIGIAN;
            }
            set
            {
                OnTHOIGIANChanging(value);
                ReportPropertyChanging("THOIGIAN");
                _THOIGIAN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("THOIGIAN");
                OnTHOIGIANChanged();
            }
        }
        private global::System.String _THOIGIAN;
        partial void OnTHOIGIANChanging(global::System.String value);
        partial void OnTHOIGIANChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LVDatabaseModel", "FK_BANGTHAN_CO_THANH__NGUOICHO", "NGUOICHOI")]
        public NGUOICHOI NGUOICHOI
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NGUOICHOI>("LVDatabaseModel.FK_BANGTHAN_CO_THANH__NGUOICHO", "NGUOICHOI").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NGUOICHOI>("LVDatabaseModel.FK_BANGTHAN_CO_THANH__NGUOICHO", "NGUOICHOI").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<NGUOICHOI> NGUOICHOIReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NGUOICHOI>("LVDatabaseModel.FK_BANGTHAN_CO_THANH__NGUOICHO", "NGUOICHOI");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<NGUOICHOI>("LVDatabaseModel.FK_BANGTHAN_CO_THANH__NGUOICHO", "NGUOICHOI", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LVDatabaseModel", "FK_BANGTHAN_THAM_GIA_MUCDO", "MUCDO")]
        public MUCDO MUCDO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MUCDO>("LVDatabaseModel.FK_BANGTHAN_THAM_GIA_MUCDO", "MUCDO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MUCDO>("LVDatabaseModel.FK_BANGTHAN_THAM_GIA_MUCDO", "MUCDO").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MUCDO> MUCDOReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MUCDO>("LVDatabaseModel.FK_BANGTHAN_THAM_GIA_MUCDO", "MUCDO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MUCDO>("LVDatabaseModel.FK_BANGTHAN_THAM_GIA_MUCDO", "MUCDO", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LVDatabaseModel", Name="BBXH_ONLINE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BBXH_ONLINE : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BBXH_ONLINE object.
        /// </summary>
        /// <param name="tAIKHOAN">Initial value of the TAIKHOAN property.</param>
        /// <param name="iDMUCDO">Initial value of the IDMUCDO property.</param>
        /// <param name="sOBUOC">Initial value of the SOBUOC property.</param>
        /// <param name="tHOIGIAN">Initial value of the THOIGIAN property.</param>
        public static BBXH_ONLINE CreateBBXH_ONLINE(global::System.String tAIKHOAN, global::System.Int32 iDMUCDO, global::System.Int32 sOBUOC, global::System.String tHOIGIAN)
        {
            BBXH_ONLINE bBXH_ONLINE = new BBXH_ONLINE();
            bBXH_ONLINE.TAIKHOAN = tAIKHOAN;
            bBXH_ONLINE.IDMUCDO = iDMUCDO;
            bBXH_ONLINE.SOBUOC = sOBUOC;
            bBXH_ONLINE.THOIGIAN = tHOIGIAN;
            return bBXH_ONLINE;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TAIKHOAN
        {
            get
            {
                return _TAIKHOAN;
            }
            set
            {
                if (_TAIKHOAN != value)
                {
                    OnTAIKHOANChanging(value);
                    ReportPropertyChanging("TAIKHOAN");
                    _TAIKHOAN = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("TAIKHOAN");
                    OnTAIKHOANChanged();
                }
            }
        }
        private global::System.String _TAIKHOAN;
        partial void OnTAIKHOANChanging(global::System.String value);
        partial void OnTAIKHOANChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDMUCDO
        {
            get
            {
                return _IDMUCDO;
            }
            set
            {
                if (_IDMUCDO != value)
                {
                    OnIDMUCDOChanging(value);
                    ReportPropertyChanging("IDMUCDO");
                    _IDMUCDO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDMUCDO");
                    OnIDMUCDOChanged();
                }
            }
        }
        private global::System.Int32 _IDMUCDO;
        partial void OnIDMUCDOChanging(global::System.Int32 value);
        partial void OnIDMUCDOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SOBUOC
        {
            get
            {
                return _SOBUOC;
            }
            set
            {
                OnSOBUOCChanging(value);
                ReportPropertyChanging("SOBUOC");
                _SOBUOC = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SOBUOC");
                OnSOBUOCChanged();
            }
        }
        private global::System.Int32 _SOBUOC;
        partial void OnSOBUOCChanging(global::System.Int32 value);
        partial void OnSOBUOCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String THOIGIAN
        {
            get
            {
                return _THOIGIAN;
            }
            set
            {
                OnTHOIGIANChanging(value);
                ReportPropertyChanging("THOIGIAN");
                _THOIGIAN = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("THOIGIAN");
                OnTHOIGIANChanged();
            }
        }
        private global::System.String _THOIGIAN;
        partial void OnTHOIGIANChanging(global::System.String value);
        partial void OnTHOIGIANChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LVDatabaseModel", Name="HINHANH")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HINHANH : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new HINHANH object.
        /// </summary>
        /// <param name="tENHINH">Initial value of the TENHINH property.</param>
        public static HINHANH CreateHINHANH(global::System.String tENHINH)
        {
            HINHANH hINHANH = new HINHANH();
            hINHANH.TENHINH = tENHINH;
            return hINHANH;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TENHINH
        {
            get
            {
                return _TENHINH;
            }
            set
            {
                if (_TENHINH != value)
                {
                    OnTENHINHChanging(value);
                    ReportPropertyChanging("TENHINH");
                    _TENHINH = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("TENHINH");
                    OnTENHINHChanged();
                }
            }
        }
        private global::System.String _TENHINH;
        partial void OnTENHINHChanging(global::System.String value);
        partial void OnTENHINHChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LVDatabaseModel", "FK_PHONGCHO_CHON_HINH_HINHANH", "PHONGCHOI")]
        public EntityCollection<PHONGCHOI> PHONGCHOIs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PHONGCHOI>("LVDatabaseModel.FK_PHONGCHO_CHON_HINH_HINHANH", "PHONGCHOI");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PHONGCHOI>("LVDatabaseModel.FK_PHONGCHO_CHON_HINH_HINHANH", "PHONGCHOI", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LVDatabaseModel", Name="MUCDO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MUCDO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MUCDO object.
        /// </summary>
        /// <param name="iDMUCDO">Initial value of the IDMUCDO property.</param>
        /// <param name="mUCDO1">Initial value of the MUCDO1 property.</param>
        public static MUCDO CreateMUCDO(global::System.Int32 iDMUCDO, global::System.String mUCDO1)
        {
            MUCDO mUCDO = new MUCDO();
            mUCDO.IDMUCDO = iDMUCDO;
            mUCDO.MUCDO1 = mUCDO1;
            return mUCDO;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDMUCDO
        {
            get
            {
                return _IDMUCDO;
            }
            set
            {
                if (_IDMUCDO != value)
                {
                    OnIDMUCDOChanging(value);
                    ReportPropertyChanging("IDMUCDO");
                    _IDMUCDO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDMUCDO");
                    OnIDMUCDOChanged();
                }
            }
        }
        private global::System.Int32 _IDMUCDO;
        partial void OnIDMUCDOChanging(global::System.Int32 value);
        partial void OnIDMUCDOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MUCDO1
        {
            get
            {
                return _MUCDO1;
            }
            set
            {
                OnMUCDO1Changing(value);
                ReportPropertyChanging("MUCDO1");
                _MUCDO1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MUCDO1");
                OnMUCDO1Changed();
            }
        }
        private global::System.String _MUCDO1;
        partial void OnMUCDO1Changing(global::System.String value);
        partial void OnMUCDO1Changed();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LVDatabaseModel", "FK_BANGTHAN_THAM_GIA_MUCDO", "BANGTHANHTICH")]
        public EntityCollection<BANGTHANHTICH> BANGTHANHTICHes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BANGTHANHTICH>("LVDatabaseModel.FK_BANGTHAN_THAM_GIA_MUCDO", "BANGTHANHTICH");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BANGTHANHTICH>("LVDatabaseModel.FK_BANGTHAN_THAM_GIA_MUCDO", "BANGTHANHTICH", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LVDatabaseModel", "FK_PHONGCHO_CHON_MUC__MUCDO", "PHONGCHOI")]
        public EntityCollection<PHONGCHOI> PHONGCHOIs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PHONGCHOI>("LVDatabaseModel.FK_PHONGCHO_CHON_MUC__MUCDO", "PHONGCHOI");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PHONGCHOI>("LVDatabaseModel.FK_PHONGCHO_CHON_MUC__MUCDO", "PHONGCHOI", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LVDatabaseModel", Name="NGUOICHOI")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NGUOICHOI : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NGUOICHOI object.
        /// </summary>
        /// <param name="tAIKHOAN">Initial value of the TAIKHOAN property.</param>
        public static NGUOICHOI CreateNGUOICHOI(global::System.String tAIKHOAN)
        {
            NGUOICHOI nGUOICHOI = new NGUOICHOI();
            nGUOICHOI.TAIKHOAN = tAIKHOAN;
            return nGUOICHOI;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TAIKHOAN
        {
            get
            {
                return _TAIKHOAN;
            }
            set
            {
                if (_TAIKHOAN != value)
                {
                    OnTAIKHOANChanging(value);
                    ReportPropertyChanging("TAIKHOAN");
                    _TAIKHOAN = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("TAIKHOAN");
                    OnTAIKHOANChanged();
                }
            }
        }
        private global::System.String _TAIKHOAN;
        partial void OnTAIKHOANChanging(global::System.String value);
        partial void OnTAIKHOANChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MATKHAU
        {
            get
            {
                return _MATKHAU;
            }
            set
            {
                OnMATKHAUChanging(value);
                ReportPropertyChanging("MATKHAU");
                _MATKHAU = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MATKHAU");
                OnMATKHAUChanged();
            }
        }
        private global::System.String _MATKHAU;
        partial void OnMATKHAUChanging(global::System.String value);
        partial void OnMATKHAUChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LVDatabaseModel", "FK_BANGTHAN_CO_THANH__NGUOICHO", "BANGTHANHTICH")]
        public EntityCollection<BANGTHANHTICH> BANGTHANHTICHes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BANGTHANHTICH>("LVDatabaseModel.FK_BANGTHAN_CO_THANH__NGUOICHO", "BANGTHANHTICH");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BANGTHANHTICH>("LVDatabaseModel.FK_BANGTHAN_CO_THANH__NGUOICHO", "BANGTHANHTICH", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LVDatabaseModel", "FK_TROCHUYE_RELATIONS_NGUOICHO", "TROCHUYEN")]
        public EntityCollection<TROCHUYEN> TROCHUYENs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TROCHUYEN>("LVDatabaseModel.FK_TROCHUYE_RELATIONS_NGUOICHO", "TROCHUYEN");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TROCHUYEN>("LVDatabaseModel.FK_TROCHUYE_RELATIONS_NGUOICHO", "TROCHUYEN", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LVDatabaseModel", Name="PHONGCHOI")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PHONGCHOI : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PHONGCHOI object.
        /// </summary>
        /// <param name="mAPHONG">Initial value of the MAPHONG property.</param>
        /// <param name="iDMUCDO">Initial value of the IDMUCDO property.</param>
        /// <param name="tENHINH">Initial value of the TENHINH property.</param>
        /// <param name="tENPHONG">Initial value of the TENPHONG property.</param>
        /// <param name="sOLUONG">Initial value of the SOLUONG property.</param>
        /// <param name="tINHTRANG">Initial value of the TINHTRANG property.</param>
        public static PHONGCHOI CreatePHONGCHOI(global::System.Int32 mAPHONG, global::System.Int32 iDMUCDO, global::System.String tENHINH, global::System.String tENPHONG, global::System.Int32 sOLUONG, global::System.Int32 tINHTRANG)
        {
            PHONGCHOI pHONGCHOI = new PHONGCHOI();
            pHONGCHOI.MAPHONG = mAPHONG;
            pHONGCHOI.IDMUCDO = iDMUCDO;
            pHONGCHOI.TENHINH = tENHINH;
            pHONGCHOI.TENPHONG = tENPHONG;
            pHONGCHOI.SOLUONG = sOLUONG;
            pHONGCHOI.TINHTRANG = tINHTRANG;
            return pHONGCHOI;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MAPHONG
        {
            get
            {
                return _MAPHONG;
            }
            set
            {
                if (_MAPHONG != value)
                {
                    OnMAPHONGChanging(value);
                    ReportPropertyChanging("MAPHONG");
                    _MAPHONG = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MAPHONG");
                    OnMAPHONGChanged();
                }
            }
        }
        private global::System.Int32 _MAPHONG;
        partial void OnMAPHONGChanging(global::System.Int32 value);
        partial void OnMAPHONGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDMUCDO
        {
            get
            {
                return _IDMUCDO;
            }
            set
            {
                OnIDMUCDOChanging(value);
                ReportPropertyChanging("IDMUCDO");
                _IDMUCDO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDMUCDO");
                OnIDMUCDOChanged();
            }
        }
        private global::System.Int32 _IDMUCDO;
        partial void OnIDMUCDOChanging(global::System.Int32 value);
        partial void OnIDMUCDOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TENHINH
        {
            get
            {
                return _TENHINH;
            }
            set
            {
                OnTENHINHChanging(value);
                ReportPropertyChanging("TENHINH");
                _TENHINH = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TENHINH");
                OnTENHINHChanged();
            }
        }
        private global::System.String _TENHINH;
        partial void OnTENHINHChanging(global::System.String value);
        partial void OnTENHINHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TENPHONG
        {
            get
            {
                return _TENPHONG;
            }
            set
            {
                OnTENPHONGChanging(value);
                ReportPropertyChanging("TENPHONG");
                _TENPHONG = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TENPHONG");
                OnTENPHONGChanged();
            }
        }
        private global::System.String _TENPHONG;
        partial void OnTENPHONGChanging(global::System.String value);
        partial void OnTENPHONGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MATKHAUPHONG
        {
            get
            {
                return _MATKHAUPHONG;
            }
            set
            {
                OnMATKHAUPHONGChanging(value);
                ReportPropertyChanging("MATKHAUPHONG");
                _MATKHAUPHONG = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MATKHAUPHONG");
                OnMATKHAUPHONGChanged();
            }
        }
        private global::System.String _MATKHAUPHONG;
        partial void OnMATKHAUPHONGChanging(global::System.String value);
        partial void OnMATKHAUPHONGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SOLUONG
        {
            get
            {
                return _SOLUONG;
            }
            set
            {
                OnSOLUONGChanging(value);
                ReportPropertyChanging("SOLUONG");
                _SOLUONG = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SOLUONG");
                OnSOLUONGChanged();
            }
        }
        private global::System.Int32 _SOLUONG;
        partial void OnSOLUONGChanging(global::System.Int32 value);
        partial void OnSOLUONGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CHUPHONG
        {
            get
            {
                return _CHUPHONG;
            }
            set
            {
                OnCHUPHONGChanging(value);
                ReportPropertyChanging("CHUPHONG");
                _CHUPHONG = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CHUPHONG");
                OnCHUPHONGChanged();
            }
        }
        private global::System.String _CHUPHONG;
        partial void OnCHUPHONGChanging(global::System.String value);
        partial void OnCHUPHONGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TINHTRANG
        {
            get
            {
                return _TINHTRANG;
            }
            set
            {
                OnTINHTRANGChanging(value);
                ReportPropertyChanging("TINHTRANG");
                _TINHTRANG = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TINHTRANG");
                OnTINHTRANGChanged();
            }
        }
        private global::System.Int32 _TINHTRANG;
        partial void OnTINHTRANGChanging(global::System.Int32 value);
        partial void OnTINHTRANGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NGUOITHANG
        {
            get
            {
                return _NGUOITHANG;
            }
            set
            {
                OnNGUOITHANGChanging(value);
                ReportPropertyChanging("NGUOITHANG");
                _NGUOITHANG = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NGUOITHANG");
                OnNGUOITHANGChanged();
            }
        }
        private global::System.String _NGUOITHANG;
        partial void OnNGUOITHANGChanging(global::System.String value);
        partial void OnNGUOITHANGChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LVDatabaseModel", "FK_PHONGCHO_CHON_HINH_HINHANH", "HINHANH")]
        public HINHANH HINHANH
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HINHANH>("LVDatabaseModel.FK_PHONGCHO_CHON_HINH_HINHANH", "HINHANH").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HINHANH>("LVDatabaseModel.FK_PHONGCHO_CHON_HINH_HINHANH", "HINHANH").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<HINHANH> HINHANHReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HINHANH>("LVDatabaseModel.FK_PHONGCHO_CHON_HINH_HINHANH", "HINHANH");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<HINHANH>("LVDatabaseModel.FK_PHONGCHO_CHON_HINH_HINHANH", "HINHANH", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LVDatabaseModel", "FK_PHONGCHO_CHON_MUC__MUCDO", "MUCDO")]
        public MUCDO MUCDO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MUCDO>("LVDatabaseModel.FK_PHONGCHO_CHON_MUC__MUCDO", "MUCDO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MUCDO>("LVDatabaseModel.FK_PHONGCHO_CHON_MUC__MUCDO", "MUCDO").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MUCDO> MUCDOReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MUCDO>("LVDatabaseModel.FK_PHONGCHO_CHON_MUC__MUCDO", "MUCDO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MUCDO>("LVDatabaseModel.FK_PHONGCHO_CHON_MUC__MUCDO", "MUCDO", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LVDatabaseModel", "FK_TROCHUYE_RELATIONS_PHONGCHO", "TROCHUYEN")]
        public EntityCollection<TROCHUYEN> TROCHUYENs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TROCHUYEN>("LVDatabaseModel.FK_TROCHUYE_RELATIONS_PHONGCHO", "TROCHUYEN");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TROCHUYEN>("LVDatabaseModel.FK_TROCHUYE_RELATIONS_PHONGCHO", "TROCHUYEN", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LVDatabaseModel", Name="TROCHUYEN")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TROCHUYEN : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TROCHUYEN object.
        /// </summary>
        /// <param name="mAPHONG">Initial value of the MAPHONG property.</param>
        /// <param name="tAIKHOAN">Initial value of the TAIKHOAN property.</param>
        /// <param name="sTT">Initial value of the STT property.</param>
        public static TROCHUYEN CreateTROCHUYEN(global::System.Int32 mAPHONG, global::System.String tAIKHOAN, global::System.Int32 sTT)
        {
            TROCHUYEN tROCHUYEN = new TROCHUYEN();
            tROCHUYEN.MAPHONG = mAPHONG;
            tROCHUYEN.TAIKHOAN = tAIKHOAN;
            tROCHUYEN.STT = sTT;
            return tROCHUYEN;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MAPHONG
        {
            get
            {
                return _MAPHONG;
            }
            set
            {
                if (_MAPHONG != value)
                {
                    OnMAPHONGChanging(value);
                    ReportPropertyChanging("MAPHONG");
                    _MAPHONG = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MAPHONG");
                    OnMAPHONGChanged();
                }
            }
        }
        private global::System.Int32 _MAPHONG;
        partial void OnMAPHONGChanging(global::System.Int32 value);
        partial void OnMAPHONGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TAIKHOAN
        {
            get
            {
                return _TAIKHOAN;
            }
            set
            {
                if (_TAIKHOAN != value)
                {
                    OnTAIKHOANChanging(value);
                    ReportPropertyChanging("TAIKHOAN");
                    _TAIKHOAN = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("TAIKHOAN");
                    OnTAIKHOANChanged();
                }
            }
        }
        private global::System.String _TAIKHOAN;
        partial void OnTAIKHOANChanging(global::System.String value);
        partial void OnTAIKHOANChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 STT
        {
            get
            {
                return _STT;
            }
            set
            {
                if (_STT != value)
                {
                    OnSTTChanging(value);
                    ReportPropertyChanging("STT");
                    _STT = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("STT");
                    OnSTTChanged();
                }
            }
        }
        private global::System.Int32 _STT;
        partial void OnSTTChanging(global::System.Int32 value);
        partial void OnSTTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NOIDUNG
        {
            get
            {
                return _NOIDUNG;
            }
            set
            {
                OnNOIDUNGChanging(value);
                ReportPropertyChanging("NOIDUNG");
                _NOIDUNG = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NOIDUNG");
                OnNOIDUNGChanged();
            }
        }
        private global::System.String _NOIDUNG;
        partial void OnNOIDUNGChanging(global::System.String value);
        partial void OnNOIDUNGChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LVDatabaseModel", "FK_TROCHUYE_RELATIONS_NGUOICHO", "NGUOICHOI")]
        public NGUOICHOI NGUOICHOI
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NGUOICHOI>("LVDatabaseModel.FK_TROCHUYE_RELATIONS_NGUOICHO", "NGUOICHOI").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NGUOICHOI>("LVDatabaseModel.FK_TROCHUYE_RELATIONS_NGUOICHO", "NGUOICHOI").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<NGUOICHOI> NGUOICHOIReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NGUOICHOI>("LVDatabaseModel.FK_TROCHUYE_RELATIONS_NGUOICHO", "NGUOICHOI");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<NGUOICHOI>("LVDatabaseModel.FK_TROCHUYE_RELATIONS_NGUOICHO", "NGUOICHOI", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LVDatabaseModel", "FK_TROCHUYE_RELATIONS_PHONGCHO", "PHONGCHOI")]
        public PHONGCHOI PHONGCHOI
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PHONGCHOI>("LVDatabaseModel.FK_TROCHUYE_RELATIONS_PHONGCHO", "PHONGCHOI").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PHONGCHOI>("LVDatabaseModel.FK_TROCHUYE_RELATIONS_PHONGCHO", "PHONGCHOI").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PHONGCHOI> PHONGCHOIReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PHONGCHOI>("LVDatabaseModel.FK_TROCHUYE_RELATIONS_PHONGCHO", "PHONGCHOI");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PHONGCHOI>("LVDatabaseModel.FK_TROCHUYE_RELATIONS_PHONGCHO", "PHONGCHOI", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
