//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace ThapHaNoi_NguyenThanhPhi.TowerHanoiService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhongChoi", Namespace="http://schemas.datacontract.org/2004/07/WebServiceForTesting")]
    public partial class PhongChoi : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CHUPHONGField;
        
        private string MATKHAUPHONGField;
        
        private int SOLUONGField;
        
        private string TENPHONGField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CHUPHONG {
            get {
                return this.CHUPHONGField;
            }
            set {
                if ((object.ReferenceEquals(this.CHUPHONGField, value) != true)) {
                    this.CHUPHONGField = value;
                    this.RaisePropertyChanged("CHUPHONG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MATKHAUPHONG {
            get {
                return this.MATKHAUPHONGField;
            }
            set {
                if ((object.ReferenceEquals(this.MATKHAUPHONGField, value) != true)) {
                    this.MATKHAUPHONGField = value;
                    this.RaisePropertyChanged("MATKHAUPHONG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SOLUONG {
            get {
                return this.SOLUONGField;
            }
            set {
                if ((this.SOLUONGField.Equals(value) != true)) {
                    this.SOLUONGField = value;
                    this.RaisePropertyChanged("SOLUONG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TENPHONG {
            get {
                return this.TENPHONGField;
            }
            set {
                if ((object.ReferenceEquals(this.TENPHONGField, value) != true)) {
                    this.TENPHONGField = value;
                    this.RaisePropertyChanged("TENPHONG");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TowerHanoiService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/CheckUser", ReplyAction="http://tempuri.org/IService1/CheckUserResponse")]
        System.IAsyncResult BeginCheckUser(string tk, string mk, System.AsyncCallback callback, object asyncState);
        
        bool EndCheckUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/CreateUser", ReplyAction="http://tempuri.org/IService1/CreateUserResponse")]
        System.IAsyncResult BeginCreateUser(string tk, string mk, System.AsyncCallback callback, object asyncState);
        
        bool EndCreateUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/DanhSachPhongChoi", ReplyAction="http://tempuri.org/IService1/DanhSachPhongChoiResponse")]
        System.IAsyncResult BeginDanhSachPhongChoi(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<ThapHaNoi_NguyenThanhPhi.TowerHanoiService.PhongChoi> EndDanhSachPhongChoi(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ThapHaNoi_NguyenThanhPhi.TowerHanoiService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CheckUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CheckUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CreateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DanhSachPhongChoiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DanhSachPhongChoiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<ThapHaNoi_NguyenThanhPhi.TowerHanoiService.PhongChoi> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<ThapHaNoi_NguyenThanhPhi.TowerHanoiService.PhongChoi>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ThapHaNoi_NguyenThanhPhi.TowerHanoiService.IService1>, ThapHaNoi_NguyenThanhPhi.TowerHanoiService.IService1 {
        
        private BeginOperationDelegate onBeginCheckUserDelegate;
        
        private EndOperationDelegate onEndCheckUserDelegate;
        
        private System.Threading.SendOrPostCallback onCheckUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginCreateUserDelegate;
        
        private EndOperationDelegate onEndCreateUserDelegate;
        
        private System.Threading.SendOrPostCallback onCreateUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginDanhSachPhongChoiDelegate;
        
        private EndOperationDelegate onEndDanhSachPhongChoiDelegate;
        
        private System.Threading.SendOrPostCallback onDanhSachPhongChoiCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<CheckUserCompletedEventArgs> CheckUserCompleted;
        
        public event System.EventHandler<CreateUserCompletedEventArgs> CreateUserCompleted;
        
        public event System.EventHandler<DanhSachPhongChoiCompletedEventArgs> DanhSachPhongChoiCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ThapHaNoi_NguyenThanhPhi.TowerHanoiService.IService1.BeginCheckUser(string tk, string mk, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCheckUser(tk, mk, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool ThapHaNoi_NguyenThanhPhi.TowerHanoiService.IService1.EndCheckUser(System.IAsyncResult result) {
            return base.Channel.EndCheckUser(result);
        }
        
        private System.IAsyncResult OnBeginCheckUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string tk = ((string)(inValues[0]));
            string mk = ((string)(inValues[1]));
            return ((ThapHaNoi_NguyenThanhPhi.TowerHanoiService.IService1)(this)).BeginCheckUser(tk, mk, callback, asyncState);
        }
        
        private object[] OnEndCheckUser(System.IAsyncResult result) {
            bool retVal = ((ThapHaNoi_NguyenThanhPhi.TowerHanoiService.IService1)(this)).EndCheckUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCheckUserCompleted(object state) {
            if ((this.CheckUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CheckUserCompleted(this, new CheckUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CheckUserAsync(string tk, string mk) {
            this.CheckUserAsync(tk, mk, null);
        }
        
        public void CheckUserAsync(string tk, string mk, object userState) {
            if ((this.onBeginCheckUserDelegate == null)) {
                this.onBeginCheckUserDelegate = new BeginOperationDelegate(this.OnBeginCheckUser);
            }
            if ((this.onEndCheckUserDelegate == null)) {
                this.onEndCheckUserDelegate = new EndOperationDelegate(this.OnEndCheckUser);
            }
            if ((this.onCheckUserCompletedDelegate == null)) {
                this.onCheckUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCheckUserCompleted);
            }
            base.InvokeAsync(this.onBeginCheckUserDelegate, new object[] {
                        tk,
                        mk}, this.onEndCheckUserDelegate, this.onCheckUserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ThapHaNoi_NguyenThanhPhi.TowerHanoiService.IService1.BeginCreateUser(string tk, string mk, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCreateUser(tk, mk, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool ThapHaNoi_NguyenThanhPhi.TowerHanoiService.IService1.EndCreateUser(System.IAsyncResult result) {
            return base.Channel.EndCreateUser(result);
        }
        
        private System.IAsyncResult OnBeginCreateUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string tk = ((string)(inValues[0]));
            string mk = ((string)(inValues[1]));
            return ((ThapHaNoi_NguyenThanhPhi.TowerHanoiService.IService1)(this)).BeginCreateUser(tk, mk, callback, asyncState);
        }
        
        private object[] OnEndCreateUser(System.IAsyncResult result) {
            bool retVal = ((ThapHaNoi_NguyenThanhPhi.TowerHanoiService.IService1)(this)).EndCreateUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCreateUserCompleted(object state) {
            if ((this.CreateUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CreateUserCompleted(this, new CreateUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CreateUserAsync(string tk, string mk) {
            this.CreateUserAsync(tk, mk, null);
        }
        
        public void CreateUserAsync(string tk, string mk, object userState) {
            if ((this.onBeginCreateUserDelegate == null)) {
                this.onBeginCreateUserDelegate = new BeginOperationDelegate(this.OnBeginCreateUser);
            }
            if ((this.onEndCreateUserDelegate == null)) {
                this.onEndCreateUserDelegate = new EndOperationDelegate(this.OnEndCreateUser);
            }
            if ((this.onCreateUserCompletedDelegate == null)) {
                this.onCreateUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCreateUserCompleted);
            }
            base.InvokeAsync(this.onBeginCreateUserDelegate, new object[] {
                        tk,
                        mk}, this.onEndCreateUserDelegate, this.onCreateUserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ThapHaNoi_NguyenThanhPhi.TowerHanoiService.IService1.BeginDanhSachPhongChoi(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDanhSachPhongChoi(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<ThapHaNoi_NguyenThanhPhi.TowerHanoiService.PhongChoi> ThapHaNoi_NguyenThanhPhi.TowerHanoiService.IService1.EndDanhSachPhongChoi(System.IAsyncResult result) {
            return base.Channel.EndDanhSachPhongChoi(result);
        }
        
        private System.IAsyncResult OnBeginDanhSachPhongChoi(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((ThapHaNoi_NguyenThanhPhi.TowerHanoiService.IService1)(this)).BeginDanhSachPhongChoi(callback, asyncState);
        }
        
        private object[] OnEndDanhSachPhongChoi(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<ThapHaNoi_NguyenThanhPhi.TowerHanoiService.PhongChoi> retVal = ((ThapHaNoi_NguyenThanhPhi.TowerHanoiService.IService1)(this)).EndDanhSachPhongChoi(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDanhSachPhongChoiCompleted(object state) {
            if ((this.DanhSachPhongChoiCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DanhSachPhongChoiCompleted(this, new DanhSachPhongChoiCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DanhSachPhongChoiAsync() {
            this.DanhSachPhongChoiAsync(null);
        }
        
        public void DanhSachPhongChoiAsync(object userState) {
            if ((this.onBeginDanhSachPhongChoiDelegate == null)) {
                this.onBeginDanhSachPhongChoiDelegate = new BeginOperationDelegate(this.OnBeginDanhSachPhongChoi);
            }
            if ((this.onEndDanhSachPhongChoiDelegate == null)) {
                this.onEndDanhSachPhongChoiDelegate = new EndOperationDelegate(this.OnEndDanhSachPhongChoi);
            }
            if ((this.onDanhSachPhongChoiCompletedDelegate == null)) {
                this.onDanhSachPhongChoiCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDanhSachPhongChoiCompleted);
            }
            base.InvokeAsync(this.onBeginDanhSachPhongChoiDelegate, null, this.onEndDanhSachPhongChoiDelegate, this.onDanhSachPhongChoiCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override ThapHaNoi_NguyenThanhPhi.TowerHanoiService.IService1 CreateChannel() {
            return new Service1ClientChannel(this);
        }
        
        private class Service1ClientChannel : ChannelBase<ThapHaNoi_NguyenThanhPhi.TowerHanoiService.IService1>, ThapHaNoi_NguyenThanhPhi.TowerHanoiService.IService1 {
            
            public Service1ClientChannel(System.ServiceModel.ClientBase<ThapHaNoi_NguyenThanhPhi.TowerHanoiService.IService1> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginCheckUser(string tk, string mk, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = tk;
                _args[1] = mk;
                System.IAsyncResult _result = base.BeginInvoke("CheckUser", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndCheckUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("CheckUser", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCreateUser(string tk, string mk, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = tk;
                _args[1] = mk;
                System.IAsyncResult _result = base.BeginInvoke("CreateUser", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndCreateUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("CreateUser", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginDanhSachPhongChoi(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("DanhSachPhongChoi", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<ThapHaNoi_NguyenThanhPhi.TowerHanoiService.PhongChoi> EndDanhSachPhongChoi(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<ThapHaNoi_NguyenThanhPhi.TowerHanoiService.PhongChoi> _result = ((System.Collections.ObjectModel.ObservableCollection<ThapHaNoi_NguyenThanhPhi.TowerHanoiService.PhongChoi>)(base.EndInvoke("DanhSachPhongChoi", _args, result)));
                return _result;
            }
        }
    }
}
