//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TowerHanoiModel", "FK_PHONGCHO_MUCDO", "MUCDO", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WebServiceForTesting.MUCDO), "PHONGCHOI", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebServiceForTesting.PHONGCHOI), true)]
[assembly: EdmRelationshipAttribute("TowerHanoiModel", "FK_THANHTICH", "MUCDO", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WebServiceForTesting.MUCDO), "THANHTICH", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebServiceForTesting.THANHTICH), true)]
[assembly: EdmRelationshipAttribute("TowerHanoiModel", "FK_THANHTICH_NGUOICHOI", "NGUOICHOI", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WebServiceForTesting.NGUOICHOI), "THANHTICH", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebServiceForTesting.THANHTICH), true)]
[assembly: EdmRelationshipAttribute("TowerHanoiModel", "NGUOICHOI_PHONGCHOI", "PHONGCHOI", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebServiceForTesting.PHONGCHOI), "NGUOICHOI", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebServiceForTesting.NGUOICHOI))]

#endregion

namespace WebServiceForTesting
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TowerHanoiEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TowerHanoiEntities object using the connection string found in the 'TowerHanoiEntities' section of the application configuration file.
        /// </summary>
        public TowerHanoiEntities() : base("name=TowerHanoiEntities", "TowerHanoiEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TowerHanoiEntities object.
        /// </summary>
        public TowerHanoiEntities(string connectionString) : base(connectionString, "TowerHanoiEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TowerHanoiEntities object.
        /// </summary>
        public TowerHanoiEntities(EntityConnection connection) : base(connection, "TowerHanoiEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MUCDO> MUCDOes
        {
            get
            {
                if ((_MUCDOes == null))
                {
                    _MUCDOes = base.CreateObjectSet<MUCDO>("MUCDOes");
                }
                return _MUCDOes;
            }
        }
        private ObjectSet<MUCDO> _MUCDOes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NGUOICHOI> NGUOICHOIs
        {
            get
            {
                if ((_NGUOICHOIs == null))
                {
                    _NGUOICHOIs = base.CreateObjectSet<NGUOICHOI>("NGUOICHOIs");
                }
                return _NGUOICHOIs;
            }
        }
        private ObjectSet<NGUOICHOI> _NGUOICHOIs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PHONGCHOI> PHONGCHOIs
        {
            get
            {
                if ((_PHONGCHOIs == null))
                {
                    _PHONGCHOIs = base.CreateObjectSet<PHONGCHOI>("PHONGCHOIs");
                }
                return _PHONGCHOIs;
            }
        }
        private ObjectSet<PHONGCHOI> _PHONGCHOIs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<THANHTICH> THANHTICHes
        {
            get
            {
                if ((_THANHTICHes == null))
                {
                    _THANHTICHes = base.CreateObjectSet<THANHTICH>("THANHTICHes");
                }
                return _THANHTICHes;
            }
        }
        private ObjectSet<THANHTICH> _THANHTICHes;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MUCDOes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMUCDOes(MUCDO mUCDO)
        {
            base.AddObject("MUCDOes", mUCDO);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NGUOICHOIs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNGUOICHOIs(NGUOICHOI nGUOICHOI)
        {
            base.AddObject("NGUOICHOIs", nGUOICHOI);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PHONGCHOIs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPHONGCHOIs(PHONGCHOI pHONGCHOI)
        {
            base.AddObject("PHONGCHOIs", pHONGCHOI);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the THANHTICHes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTHANHTICHes(THANHTICH tHANHTICH)
        {
            base.AddObject("THANHTICHes", tHANHTICH);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TowerHanoiModel", Name="MUCDO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MUCDO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MUCDO object.
        /// </summary>
        /// <param name="sODIA">Initial value of the SODIA property.</param>
        public static MUCDO CreateMUCDO(global::System.Int16 sODIA)
        {
            MUCDO mUCDO = new MUCDO();
            mUCDO.SODIA = sODIA;
            return mUCDO;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 SODIA
        {
            get
            {
                return _SODIA;
            }
            set
            {
                if (_SODIA != value)
                {
                    OnSODIAChanging(value);
                    ReportPropertyChanging("SODIA");
                    _SODIA = StructuralObject.SetValidValue(value, "SODIA");
                    ReportPropertyChanged("SODIA");
                    OnSODIAChanged();
                }
            }
        }
        private global::System.Int16 _SODIA;
        partial void OnSODIAChanging(global::System.Int16 value);
        partial void OnSODIAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MOTA
        {
            get
            {
                return _MOTA;
            }
            set
            {
                OnMOTAChanging(value);
                ReportPropertyChanging("MOTA");
                _MOTA = StructuralObject.SetValidValue(value, true, "MOTA");
                ReportPropertyChanged("MOTA");
                OnMOTAChanged();
            }
        }
        private global::System.String _MOTA;
        partial void OnMOTAChanging(global::System.String value);
        partial void OnMOTAChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TowerHanoiModel", "FK_PHONGCHO_MUCDO", "PHONGCHOI")]
        public EntityCollection<PHONGCHOI> PHONGCHOIs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PHONGCHOI>("TowerHanoiModel.FK_PHONGCHO_MUCDO", "PHONGCHOI");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PHONGCHOI>("TowerHanoiModel.FK_PHONGCHO_MUCDO", "PHONGCHOI", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TowerHanoiModel", "FK_THANHTICH", "THANHTICH")]
        public EntityCollection<THANHTICH> THANHTICHes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<THANHTICH>("TowerHanoiModel.FK_THANHTICH", "THANHTICH");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<THANHTICH>("TowerHanoiModel.FK_THANHTICH", "THANHTICH", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TowerHanoiModel", Name="NGUOICHOI")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NGUOICHOI : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NGUOICHOI object.
        /// </summary>
        /// <param name="tAIKHOAN">Initial value of the TAIKHOAN property.</param>
        public static NGUOICHOI CreateNGUOICHOI(global::System.String tAIKHOAN)
        {
            NGUOICHOI nGUOICHOI = new NGUOICHOI();
            nGUOICHOI.TAIKHOAN = tAIKHOAN;
            return nGUOICHOI;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TAIKHOAN
        {
            get
            {
                return _TAIKHOAN;
            }
            set
            {
                if (_TAIKHOAN != value)
                {
                    OnTAIKHOANChanging(value);
                    ReportPropertyChanging("TAIKHOAN");
                    _TAIKHOAN = StructuralObject.SetValidValue(value, false, "TAIKHOAN");
                    ReportPropertyChanged("TAIKHOAN");
                    OnTAIKHOANChanged();
                }
            }
        }
        private global::System.String _TAIKHOAN;
        partial void OnTAIKHOANChanging(global::System.String value);
        partial void OnTAIKHOANChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MATKHAU
        {
            get
            {
                return _MATKHAU;
            }
            set
            {
                OnMATKHAUChanging(value);
                ReportPropertyChanging("MATKHAU");
                _MATKHAU = StructuralObject.SetValidValue(value, true, "MATKHAU");
                ReportPropertyChanged("MATKHAU");
                OnMATKHAUChanged();
            }
        }
        private global::System.String _MATKHAU;
        partial void OnMATKHAUChanging(global::System.String value);
        partial void OnMATKHAUChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TowerHanoiModel", "FK_THANHTICH_NGUOICHOI", "THANHTICH")]
        public EntityCollection<THANHTICH> THANHTICHes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<THANHTICH>("TowerHanoiModel.FK_THANHTICH_NGUOICHOI", "THANHTICH");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<THANHTICH>("TowerHanoiModel.FK_THANHTICH_NGUOICHOI", "THANHTICH", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TowerHanoiModel", "NGUOICHOI_PHONGCHOI", "PHONGCHOI")]
        public EntityCollection<PHONGCHOI> PHONGCHOIs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PHONGCHOI>("TowerHanoiModel.NGUOICHOI_PHONGCHOI", "PHONGCHOI");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PHONGCHOI>("TowerHanoiModel.NGUOICHOI_PHONGCHOI", "PHONGCHOI", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TowerHanoiModel", Name="PHONGCHOI")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PHONGCHOI : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PHONGCHOI object.
        /// </summary>
        /// <param name="mAPHONG">Initial value of the MAPHONG property.</param>
        /// <param name="sODIA">Initial value of the SODIA property.</param>
        public static PHONGCHOI CreatePHONGCHOI(global::System.Int32 mAPHONG, global::System.Int16 sODIA)
        {
            PHONGCHOI pHONGCHOI = new PHONGCHOI();
            pHONGCHOI.MAPHONG = mAPHONG;
            pHONGCHOI.SODIA = sODIA;
            return pHONGCHOI;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MAPHONG
        {
            get
            {
                return _MAPHONG;
            }
            set
            {
                if (_MAPHONG != value)
                {
                    OnMAPHONGChanging(value);
                    ReportPropertyChanging("MAPHONG");
                    _MAPHONG = StructuralObject.SetValidValue(value, "MAPHONG");
                    ReportPropertyChanged("MAPHONG");
                    OnMAPHONGChanged();
                }
            }
        }
        private global::System.Int32 _MAPHONG;
        partial void OnMAPHONGChanging(global::System.Int32 value);
        partial void OnMAPHONGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 SODIA
        {
            get
            {
                return _SODIA;
            }
            set
            {
                OnSODIAChanging(value);
                ReportPropertyChanging("SODIA");
                _SODIA = StructuralObject.SetValidValue(value, "SODIA");
                ReportPropertyChanged("SODIA");
                OnSODIAChanged();
            }
        }
        private global::System.Int16 _SODIA;
        partial void OnSODIAChanging(global::System.Int16 value);
        partial void OnSODIAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TENPHONG
        {
            get
            {
                return _TENPHONG;
            }
            set
            {
                OnTENPHONGChanging(value);
                ReportPropertyChanging("TENPHONG");
                _TENPHONG = StructuralObject.SetValidValue(value, true, "TENPHONG");
                ReportPropertyChanged("TENPHONG");
                OnTENPHONGChanged();
            }
        }
        private global::System.String _TENPHONG;
        partial void OnTENPHONGChanging(global::System.String value);
        partial void OnTENPHONGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SOLUONG
        {
            get
            {
                return _SOLUONG;
            }
            set
            {
                OnSOLUONGChanging(value);
                ReportPropertyChanging("SOLUONG");
                _SOLUONG = StructuralObject.SetValidValue(value, "SOLUONG");
                ReportPropertyChanged("SOLUONG");
                OnSOLUONGChanged();
            }
        }
        private Nullable<global::System.Int32> _SOLUONG;
        partial void OnSOLUONGChanging(Nullable<global::System.Int32> value);
        partial void OnSOLUONGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TINHTRANG
        {
            get
            {
                return _TINHTRANG;
            }
            set
            {
                OnTINHTRANGChanging(value);
                ReportPropertyChanging("TINHTRANG");
                _TINHTRANG = StructuralObject.SetValidValue(value, true, "TINHTRANG");
                ReportPropertyChanged("TINHTRANG");
                OnTINHTRANGChanged();
            }
        }
        private global::System.String _TINHTRANG;
        partial void OnTINHTRANGChanging(global::System.String value);
        partial void OnTINHTRANGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MATKHAU
        {
            get
            {
                return _MATKHAU;
            }
            set
            {
                OnMATKHAUChanging(value);
                ReportPropertyChanging("MATKHAU");
                _MATKHAU = StructuralObject.SetValidValue(value, true, "MATKHAU");
                ReportPropertyChanged("MATKHAU");
                OnMATKHAUChanged();
            }
        }
        private global::System.String _MATKHAU;
        partial void OnMATKHAUChanging(global::System.String value);
        partial void OnMATKHAUChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NGUOITHANG
        {
            get
            {
                return _NGUOITHANG;
            }
            set
            {
                OnNGUOITHANGChanging(value);
                ReportPropertyChanging("NGUOITHANG");
                _NGUOITHANG = StructuralObject.SetValidValue(value, true, "NGUOITHANG");
                ReportPropertyChanged("NGUOITHANG");
                OnNGUOITHANGChanged();
            }
        }
        private global::System.String _NGUOITHANG;
        partial void OnNGUOITHANGChanging(global::System.String value);
        partial void OnNGUOITHANGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CHUPHONG
        {
            get
            {
                return _CHUPHONG;
            }
            set
            {
                OnCHUPHONGChanging(value);
                ReportPropertyChanging("CHUPHONG");
                _CHUPHONG = StructuralObject.SetValidValue(value, true, "CHUPHONG");
                ReportPropertyChanged("CHUPHONG");
                OnCHUPHONGChanged();
            }
        }
        private global::System.String _CHUPHONG;
        partial void OnCHUPHONGChanging(global::System.String value);
        partial void OnCHUPHONGChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TowerHanoiModel", "FK_PHONGCHO_MUCDO", "MUCDO")]
        public MUCDO MUCDO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MUCDO>("TowerHanoiModel.FK_PHONGCHO_MUCDO", "MUCDO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MUCDO>("TowerHanoiModel.FK_PHONGCHO_MUCDO", "MUCDO").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MUCDO> MUCDOReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MUCDO>("TowerHanoiModel.FK_PHONGCHO_MUCDO", "MUCDO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MUCDO>("TowerHanoiModel.FK_PHONGCHO_MUCDO", "MUCDO", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TowerHanoiModel", "NGUOICHOI_PHONGCHOI", "NGUOICHOI")]
        public EntityCollection<NGUOICHOI> NGUOICHOIs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<NGUOICHOI>("TowerHanoiModel.NGUOICHOI_PHONGCHOI", "NGUOICHOI");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<NGUOICHOI>("TowerHanoiModel.NGUOICHOI_PHONGCHOI", "NGUOICHOI", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TowerHanoiModel", Name="THANHTICH")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class THANHTICH : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new THANHTICH object.
        /// </summary>
        /// <param name="tAIKHOAN">Initial value of the TAIKHOAN property.</param>
        /// <param name="sODIA">Initial value of the SODIA property.</param>
        public static THANHTICH CreateTHANHTICH(global::System.String tAIKHOAN, global::System.Int16 sODIA)
        {
            THANHTICH tHANHTICH = new THANHTICH();
            tHANHTICH.TAIKHOAN = tAIKHOAN;
            tHANHTICH.SODIA = sODIA;
            return tHANHTICH;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TAIKHOAN
        {
            get
            {
                return _TAIKHOAN;
            }
            set
            {
                if (_TAIKHOAN != value)
                {
                    OnTAIKHOANChanging(value);
                    ReportPropertyChanging("TAIKHOAN");
                    _TAIKHOAN = StructuralObject.SetValidValue(value, false, "TAIKHOAN");
                    ReportPropertyChanged("TAIKHOAN");
                    OnTAIKHOANChanged();
                }
            }
        }
        private global::System.String _TAIKHOAN;
        partial void OnTAIKHOANChanging(global::System.String value);
        partial void OnTAIKHOANChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 SODIA
        {
            get
            {
                return _SODIA;
            }
            set
            {
                if (_SODIA != value)
                {
                    OnSODIAChanging(value);
                    ReportPropertyChanging("SODIA");
                    _SODIA = StructuralObject.SetValidValue(value, "SODIA");
                    ReportPropertyChanged("SODIA");
                    OnSODIAChanged();
                }
            }
        }
        private global::System.Int16 _SODIA;
        partial void OnSODIAChanging(global::System.Int16 value);
        partial void OnSODIAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.TimeSpan> THOIGIAN
        {
            get
            {
                return _THOIGIAN;
            }
            set
            {
                OnTHOIGIANChanging(value);
                ReportPropertyChanging("THOIGIAN");
                _THOIGIAN = StructuralObject.SetValidValue(value, "THOIGIAN");
                ReportPropertyChanged("THOIGIAN");
                OnTHOIGIANChanged();
            }
        }
        private Nullable<global::System.TimeSpan> _THOIGIAN;
        partial void OnTHOIGIANChanging(Nullable<global::System.TimeSpan> value);
        partial void OnTHOIGIANChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> SOBUOCCHUYEN
        {
            get
            {
                return _SOBUOCCHUYEN;
            }
            set
            {
                OnSOBUOCCHUYENChanging(value);
                ReportPropertyChanging("SOBUOCCHUYEN");
                _SOBUOCCHUYEN = StructuralObject.SetValidValue(value, "SOBUOCCHUYEN");
                ReportPropertyChanged("SOBUOCCHUYEN");
                OnSOBUOCCHUYENChanged();
            }
        }
        private Nullable<global::System.Int16> _SOBUOCCHUYEN;
        partial void OnSOBUOCCHUYENChanging(Nullable<global::System.Int16> value);
        partial void OnSOBUOCCHUYENChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TowerHanoiModel", "FK_THANHTICH", "MUCDO")]
        public MUCDO MUCDO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MUCDO>("TowerHanoiModel.FK_THANHTICH", "MUCDO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MUCDO>("TowerHanoiModel.FK_THANHTICH", "MUCDO").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MUCDO> MUCDOReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MUCDO>("TowerHanoiModel.FK_THANHTICH", "MUCDO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MUCDO>("TowerHanoiModel.FK_THANHTICH", "MUCDO", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TowerHanoiModel", "FK_THANHTICH_NGUOICHOI", "NGUOICHOI")]
        public NGUOICHOI NGUOICHOI
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NGUOICHOI>("TowerHanoiModel.FK_THANHTICH_NGUOICHOI", "NGUOICHOI").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NGUOICHOI>("TowerHanoiModel.FK_THANHTICH_NGUOICHOI", "NGUOICHOI").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<NGUOICHOI> NGUOICHOIReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NGUOICHOI>("TowerHanoiModel.FK_THANHTICH_NGUOICHOI", "NGUOICHOI");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<NGUOICHOI>("TowerHanoiModel.FK_THANHTICH_NGUOICHOI", "NGUOICHOI", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
